# -----------------
kind: Deployment
apiVersion: apps/v1
metadata:
#<SERVICE_NAME>
  name: yyy-prd-celery
  namespace: <NAME_SPACE>
  labels:
      app: yyy-prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yyy-prd
  template:
    metadata:
      labels:
        app: yyy-prd
    spec:
      containers:
      - name: yyy-celery
        image: <IMAGE_NAME>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command:
              - cat
              - /code/Dockerfile
          initialDelaySeconds: 5
          periodSeconds: 5
        # 定义环境变量
        env:
          - name: MODE
            value: <ENV>
          - name: app_logs_ityyy
            value: "stdout"
          #- name: app_logs_it_yyy
            #value: "/usr/bin/.*log"
        ports:
          - containerPort: 8000
            protocol: TCP
        command: ["celery", "-A", "task", "worker", "-l", "info", "-Q", "yyy.regular,yyy.execute", "-n", "yyy@%h"]
      imagePullSecrets:
        - name: regsecret
