# -----------------
kind: Deployment
apiVersion: apps/v1
metadata:
#<SERVICE_NAME>
  name: yyy-prd
  namespace: <NAME_SPACE>
  labels:
      app: yyy-prd-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yyy-prd-service
  template:
    metadata:
      labels:
        app: yyy-prd-service
    spec:
      containers:
      - name: yyy
        image: <IMAGE_NAME>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command:
              - cat
              - /code/Dockerfile
          initialDelaySeconds: 5
          periodSeconds: 5
        # 定义环境变量
        env:
          - name: MODE
            value: <ENV>
          - name: app_logs_ityyy
            value: "stdout"
          #- name: app_logs_ityyy
            #value: "/usr/bin/.*log"
        ports:
          - containerPort: 8000
            protocol: TCP
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
      imagePullSecrets:
        - name: regsecret
