# Generated by Django 2.2.2 on 2019-09-21 21:44

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('user_id', models.CharField(help_text='用户ID', max_length=10)),
                ('name', models.CharField(help_text='任务名称', max_length=128)),
                ('keyword', models.CharField(help_text='关键词', max_length=128)),
                ('first_search_time', models.DateTimeField(auto_now_add=True)),
                ('next_search_time', models.DateTimeField(auto_now=True)),
                ('finished_time', models.DateTimeField(auto_now=True)),
                ('mail', models.TextField(default='', help_text='通知邮箱列表', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('user_id', models.CharField(help_text='用户ID', max_length=10)),
                ('token', models.CharField(max_length=40, validators=[utils.valid_token])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leakage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('user_id', models.CharField(help_text='用户ID', max_length=10)),
                ('keyword', models.CharField(db_index=True, help_text='关键字名称', max_length=128)),
                ('sha', models.CharField(help_text='文件hash值', max_length=128)),
                ('fragment', models.TextField(help_text='结果详情')),
                ('html_url', models.CharField(help_text='结果地址', max_length=2048)),
                ('file_name', models.CharField(help_text='所在文件名', max_length=128)),
                ('repo_name', models.CharField(help_text='仓库名', max_length=128)),
                ('repo_url', models.CharField(help_text='仓库地址', max_length=128)),
                ('user_avatar', models.CharField(help_text='用户头像', max_length=128)),
                ('user_name', models.CharField(help_text='用户名', max_length=128)),
                ('user_url', models.CharField(help_text='用户地址', max_length=128)),
                ('hash_value', models.CharField(db_index=True, help_text='hash值', max_length=64)),
                ('leakage_status', models.IntegerField(choices=[(0, '未处理'), (1, '已处理'), (2, '白名单')], default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Task')),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
    ]
